sudo: required
language: python
os: linux
python: 3.6
env:
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="9"
  - TRAVIS_NODE_VERSION="10"
matrix:
  include:
    - os: osx  
      language: generic
      env: TRAVIS_NODE_VERSION="8"
    - os: osx  
      language: generic
      env: TRAVIS_NODE_VERSION="9"
    - os: osx  
      language: generic
      env: TRAVIS_NODE_VERSION="10"
services:
  - docker
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
       sudo apt-get install build-essential libxi-dev libglu1-mesa-dev libglew-dev
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update
       brew upgrade python
    fi
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - cd minos/server && npm install && cd ../..
  - pip3 install -e . -r requirements.txt
script: 
  - echo
